# Generated by Django 2.1.7 on 2019-04-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True),
        ),
    ]
